//+------------------------------------------------------------------+
//| DEMO-SYNTHETIC-NOT-TRADABLE.mq5                                          
//| Generated by AGLE Strategy Factory -- GEN 14 QUALIFIED           
//| spec_hash : 1a14fb2368f053159269e0bfcfeb9732f42728c1eff20d57d434f4ddfde2dc7b                                     
//| mechanism : DEMONSTRATION ONLY -- fade the 3rd consecutive same-direction H1 bar
//| framework : streak_fade   symbol: EURUSD
//| Parameters below are FROZEN. Changing them voids qualification.  
//+------------------------------------------------------------------+
#property strict
#include <Trade\Trade.mqh>
CTrade trade;

input double InpRiskPercent  = 0.50;    // risk per trade (% of equity)
input int    InpHoldBars     = 4;      // frozen holding horizon
input int    InpStreakK      = 3;      // frozen streak length
input int    InpHourFrom     = 7;
input int    InpHourTo       = 17;
input bool   UseVolFilter    = true;
input bool   UseNR7Filter    = false;
input int    InpMagic        = 20260820;

datetime lastBar = 0;
int      barsInTrade = 0;

int HourOfBar() { MqlDateTime t; TimeToStruct(iTime(_Symbol,_Period,1), t); return t.hour; }
bool HourAllowed() { int h = HourOfBar(); return (h >= InpHourFrom && h < InpHourTo); }

int StreakLength()
{
   int dir = 0, len = 0;
   for(int i = 1; i <= 20; i++)
   {
      int d = (iClose(_Symbol,_Period,i) > iClose(_Symbol,_Period,i+1)) ? 1 : -1;
      if(i == 1) { dir = d; len = 1; }
      else if(d == dir) len++;
      else break;
   }
   return dir * len;
}

double ATR(int period) { return iATR(_Symbol, _Period, period, 1); }

bool VolFilterOk()
{
   if(!UseVolFilter) return(true);
   return(ATR(14) > ATR(50));
}

bool IsNR7()
{
   double r0 = iHigh(_Symbol,_Period,1) - iLow(_Symbol,_Period,1);
   for(int i = 2; i <= 7; i++)
      if(iHigh(_Symbol,_Period,i) - iLow(_Symbol,_Period,i) < r0) return(false);
   return(true);
}

bool IsWeekendGapBar()
{ return((iTime(_Symbol,_Period,1) - iTime(_Symbol,_Period,2)) > 40*3600); }

double Highest(int n) { return iHigh(_Symbol,_Period,iHighest(_Symbol,_Period,MODE_HIGH,n,2)); }
double Lowest (int n) { return iLow (_Symbol,_Period,iLowest (_Symbol,_Period,MODE_LOW ,n,2)); }

int Signal()
{
   int streak = StreakLength();
   if(MathAbs(streak) < 3) return(0);
   if(!HourAllowed()) return(0);
   if(!VolFilterOk()) return(0);
   return(streak > 0 ? -1 : 1);   // fade the run
}

double LotSize()
{
   double equity = AccountInfoDouble(ACCOUNT_EQUITY);
   double risk   = equity * InpRiskPercent / 100.0;
   double atr    = ATR(14);
   double tickV  = SymbolInfoDouble(_Symbol, SYMBOL_TRADE_TICK_VALUE);
   double tickS  = SymbolInfoDouble(_Symbol, SYMBOL_TRADE_TICK_SIZE);
   if(atr <= 0 || tickV <= 0 || tickS <= 0) return(SymbolInfoDouble(_Symbol,SYMBOL_VOLUME_MIN));
   double lots = risk / ((atr * 2.0 / tickS) * tickV);
   double mn = SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_MIN);
   double mx = SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_MAX);
   double st = SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_STEP);
   lots = MathFloor(lots/st)*st;
   return(MathMax(mn, MathMin(mx, lots)));
}

int OnInit() { trade.SetExpertMagicNumber(InpMagic); return(INIT_SUCCEEDED); }

void OnTick()
{
   datetime t = iTime(_Symbol, _Period, 0);
   if(t == lastBar) return;             // one decision per closed bar
   lastBar = t;

   if(PositionSelect(_Symbol))
   {
      barsInTrade++;
      if(barsInTrade >= InpHoldBars) { trade.PositionClose(_Symbol); barsInTrade = 0; }
      return;
   }

   int sig = Signal();
   if(sig == 0) return;

   double lots = LotSize();
   double atr  = ATR(14);
   double ask  = SymbolInfoDouble(_Symbol, SYMBOL_ASK);
   double bid  = SymbolInfoDouble(_Symbol, SYMBOL_BID);
   if(sig > 0) trade.Buy (lots, _Symbol, ask, ask - 2.0*atr, ask + 3.0*atr);
   else        trade.Sell(lots, _Symbol, bid, bid + 2.0*atr, bid - 3.0*atr);
   barsInTrade = 0;
}
